language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: p6pHuKQ7fgA2KlsqUcmUsKnUG36ut1DsQjTVANzXpOplPFTM79RUStGBWg9WpUE8lN1lik0fsz4b6cjWXfA37RZ1YmxynE5NUidbnlymNWpJYad0xUJNntMjXlKvRLQREAZp0zE5vwrSC71jUhwnwHIJmsJ04xdMoq2uNASs7RnF4JuNNEAyZOERX5xFcW0mKMTAcHXW+6gl/HYzDeXaED5zlIHbgjii5W070en7sep1IJnaGBbSbIL3ZaG810ByQUPMLPXvON+WMzoxqed52OV/j76vedX0/Lp6ztbtV/aohmsYcIWRR5q+qrH145WYPfottgdMaPRfc9f6pQelym3GlMQgWmdpIegj28dvh1SR72NTLQ46t27de73BwCNlmVQ2oYnHjVWoKfTa/4JY26O7QvbUgPmKF06U8Bm/SuUXNZi1YMuwolibsSnSD7/TRo07Sh/5UBXRDKNaAs9QQ/ItZBRuqHJEj5Ud3rtmiayh4E1iRXRDJnmK4w2D86jmkv9qjIeXzrltc7pNal1YhZDu5+1hwxZH/knJXybxKnUAgP7PLXeyO2xZA15UfzSuFzCVGGDMkLyrzdNbF4GAz6E/oY5DORncxGoB6pmQHSwP8aL6rRjq0qZ6yFsEsZoUjGmlhw+X+OdTaMrZUwunfz3D6OECZy0ohrVEql6xL6I=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: QJcr8GbvjbTuOWHoPf/TUzHvWsScETHOncRmsH3E/KplTUte+iJQWulSNTq3RCc6/uC0YDVJXvhaS19Eu8z3RDvf2jtQrjYW3+mSBqsBWGBTNNK+OhDWO/NA+t5P0iVwLK4ksQaNL7UcI0inOiXXObgPU3a4GTRMKlLnC9ACEgtMVwOmTLICNOb9TjTLff11I1F9MYoPZh5CthKEujUiazu870TqWbTKfiltr4hX7hJYp1yuvTmX+zHAFx+pWA3hGCbyBkumdnqyBolnZoduXXNyvyCXQVtAEdNa7fJnrNvvhmtfPzwBfwcpeLdL/wD5kOkFIrmv68BJxQVsxCJ0GtzGE6fvJtpW+GKbMUSPufut3J3eZx7mBfotk0fh0G3+XX95kkQwaF0LDMgMGS/4fvYGRF8SQvAWrhQygMc4D3qxbjYGon0m5ZMwRYymqvWleAmEZoeqG0JiC1xnDQn4EPROCqId98zmYjJEVY4wooq+85fctP835MXc7TRnhhgYiSUP9KFtU0oow2UuyYwU4WuipevEijzPM7HAfDpMVce1jEpLGcdzCsyU2A1YgKuCHqKpL7qdtDtB4+my0n/EotM6kc98CIqhgUqe5/5v+bqb3zOTQxryvQH9wvjUtt7sDU6U/ItU46WVlyu6ROrv8PMoCaJyUyLB1ar9dAteXSI=
sudo: false
